### ISSUE TITLE
Invalid Parameter – yii\base\InvalidParamException

### ISSUE THREAD

**Issue by ddeshar** [mrlco/yii2-jalali-datepicker#1]
Hello sir! first of all thank you sir for ur date picker yii2 widget 
but i am not able to use your widget i have install it from composer as ur instruction but it say 

Invalid Parameter – yii\base\InvalidParamException

so i am confused that what mistake i have done so will you please help me by finding what mistake i have done? i have attached my code photos also 
![picture of error on browser ](https://cloud.githubusercontent.com/assets/14323613/12582261/91f83e22-c46e-11e5-8cc9-1d914a2b298f.png)
![picture of my code](https://cloud.githubusercontent.com/assets/14323613/12582262/91f93afc-c46e-11e5-89e7-b1c2516185f7.png)

**Comment by mehrna** [comment]
Hi. Sorry for the late reply.
This is caused by your **OS** (Microsoft Windows), though this is because of directory separator for assets path. It will be fix as soon as possible.

**Comment by mehrna** [comment]
Fixed with commit 36bfd9ade6e6754520b9b53899fc686414922148
