### ISSUE TITLE
persian-date is not defined

### ISSUE THREAD

**Issue by majid-jafari** [mrlco/yii2-jalali-datepicker#3]
hi,this js error is because "persian-date.js" not loaded

**Comment by bit-prophet** [comment]
Hi
It's a typing mistake, check file "mrlco\yii2-jalali-datepicker\DateAsset.php"
In line 21 change "an-date-0.1.8.js" to "persian-date-0.1.8.js"

**Comment by majid-jafari** [comment]
hi @mohsennouri 
Thank you...
