### ISSUE TITLE
change font

### ISSUE THREAD

**Issue by fazelit** [mrlco/yii2-jalali-datepicker#4]
سلام 
چطور میتونم فونت رو تغییر بدم؟

**Comment by mehrna** [comment]
Hello Dear @fazelit,
As this repo is just a wrapper written in Yii2 PHP framework that renders a [Persian Web Toolkit](http://babakhani.github.io/PersianWebToolkit)'s [Persian Date Picker](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/) ([Reza Babakhani](https://github.com/babakhani)'s nice work.), so the question is not related to this repo.

By the way you could edit the `.datepicker-plot-area` css class in the main css file ([persian-datepicker.css](http://babakhani.github.io/PersianWebToolkit/doc/lib/persian-datepicker/dist/css/persian-datepicker.css)) of [Persian Date Picker](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/). (I really do not recommend!)

For better approach that much like a best practice, simply add this css class to your main parojects's css file and add anything you need like this:
```css
.datepicker-plot-area {
    font: 12px "YOUR_FONT_NAME"!important;
}
```
Beware of adding `!important` in front of the property and also change **YOUR_FONT_NAME** to your custom font name!
