### ISSUE TITLE
gridview filter

### ISSUE THREAD

**Issue by siromidz** [mrlco/yii2-jalali-datepicker#5]
hi
how can I use this DatePicker to filter a date column in a Gridview?
I save gregorian date and show Jalali date

**Comment by mehrna** [comment]
Hello @siromidz
Just use it  **as a widget** in your _GridView's attribute_  like this:

```php
[
    'attribute' => 'updated_at',
    'value' => 'updated_at',
    'filter' => mrlco\datepicker\Datepicker::widget([
        'model' => $searchModel,
        'attribute' => 'updated_at',
        'template' => '{addon}{input}',
        'clientOptions' => [
            'format' => 'YYYY/MM/DD' // Use any format (or any other options) you need
        ]
    ]),
    'format' => 'html',
],

**Comment by siromidz** [comment]
thanks
but something else
when I use it, it is not empty.

**Comment by mehrna** [comment]
> when I use it, it is not empty.

What do you mean?

**Comment by siromidz** [comment]
> > when I use it, it is not empty.
> 
> What do you mean?

![Untitled](https://user-images.githubusercontent.com/12757236/109387231-66bf0180-7915-11eb-82d9-fa9d60f08d6a.png)

how can I empty the input?(1399/12/09)

**Comment by mehrna** [comment]
This issue is related to [this](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/) library.
 Have you ever seen the [options of Babakhani's Persian Datepicker](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/#options) ?

maybe you should set `initialValue` to false.

**Comment by siromidz** [comment]
thanks. 
solved.
